package com.evecta.auth.model;

public enum AuditAction {
  LOGIN,
  LOGOUT,
  CAMBIO_CLAVE,
  SOLICITUD_RECUPERACION_CLAVE,
  USUARIO_CREADO,
  USUARIO_ACTUALIZADO,
  USUARIO_ACTIVADO,
  USUARIO_DESACTIVADO,
  ROL_ACTUALIZADO
}
